import sys
from typing import Iterator, List, Optional, Tuple

class PanicError(Exception): ...
class ListenerClosedError(Exception): ...

class VariantKind:
    @property
    def is_data(self) -> bool: ...
    @property
    def is_code(self) -> bool: ...
    @property
    def proof_size(self) -> int: ...
    @property
    def resigned(self) -> bool: ...
    @property
    def merkle_suffix(self) -> int: ...
    @property
    def kind(self) -> str: ...
    def __repr__(self) -> str: ...

class AccumulatorConfig:
    max_fec_sets_per_slot: int
    stuck_batch_timeout_ms: int
    def __init__(
        self,
        max_fec_sets_per_slot: Optional[int] = None,
        stuck_batch_timeout_ms: Optional[int] = None,
    ) -> None: ...
    def __repr__(self) -> str: ...

class ListenerOptions:
    recv_buf: int
    max_age: int
    busy_poll_us: Optional[int]
    pool_size: int
    enable_fec: bool
    disable_salvage_delivery: bool
    accumulator: AccumulatorConfig
    def __init__(
        self,
        recv_buf: Optional[int] = None,
        max_age: Optional[int] = None,
        busy_poll_us: Optional[int] = None,
        pool_size: Optional[int] = None,
        enable_fec: Optional[bool] = None,
        disable_salvage_delivery: Optional[bool] = None,
        accumulator: Optional[AccumulatorConfig] = None,
        busy_poll_disabled: bool = False,
    ) -> None: ...
    def __repr__(self) -> str: ...

class RawShred:
    @property
    def slot(self) -> int: ...
    @property
    def index(self) -> int: ...
    @property
    def payload_len(self) -> int: ...
    def __repr__(self) -> str: ...

class ShredIter:
    def __iter__(self) -> "ShredIter": ...
    def __next__(self) -> RawShred: ...

class ShredListener:
    def __init__(self, port: int, options: Optional[ListenerOptions] = None) -> None: ...
    @staticmethod
    def bind(port: int) -> "ShredListener": ...
    @staticmethod
    def bind_with_options(port: int, options: ListenerOptions) -> "ShredListener": ...
    @staticmethod
    def offline() -> "ShredListener": ...
    if sys.platform != "win32":
        @staticmethod
        def from_fd(fd: int, options: Optional[ListenerOptions] = None) -> "ShredListener": ...
    def close(self) -> None: ...
    def local_addr(self) -> str: ...
    @property
    def slot_count(self) -> int: ...
    def handle_packet(
        self, data: bytes
    ) -> Optional[Tuple[int, List[bytes]]]: ...
    def __iter__(self) -> Iterator[Tuple[int, List[bytes]]]: ...
    def __next__(self) -> Tuple[int, List[bytes]]: ...
    def shreds(self) -> ShredIter: ...
    @property
    def pool_exhausted_count(self) -> int: ...
    @property
    def last_io_error_kind(self) -> Optional[str]: ...
    @property
    def busy_poll_active(self) -> bool: ...
    @property
    def data_shred_count_total(self) -> int: ...
    @property
    def code_shred_count_total(self) -> int: ...
    @property
    def bytes_received(self) -> int: ...
    @property
    def unparseable_packets(self) -> int: ...
    @property
    def unparseable_too_short(self) -> int: ...
    @property
    def unparseable_variant(self) -> int: ...
    @property
    def unparseable_payload(self) -> int: ...
    @property
    def unparseable_slot_range(self) -> int: ...
    @property
    def dropped_known_slots(self) -> int: ...
    @property
    def harvested_batches_total(self) -> int: ...
    @property
    def decode_errors_total(self) -> int: ...
    @property
    def fec_recoveries_total(self) -> int: ...
    @property
    def fec_recovery_failures_total(self) -> int: ...
    @property
    def batches_skipped_total(self) -> int: ...
    @property
    def batches_decoded_streaming_total(self) -> int: ...
    @property
    def batches_decoded_fallback_total(self) -> int: ...
    @property
    def slots_completed_total(self) -> int: ...
    @property
    def slots_evicted_by_age(self) -> int: ...
    @property
    def salvaged_tail_tx_total(self) -> int: ...
    @property
    def fec_sets_discarded_unused_total(self) -> int: ...
    @property
    def fec_sets_evicted_early_total(self) -> int: ...
    @property
    def batches_force_finalized_corrupted_total(self) -> int: ...
    @property
    def batches_force_finalized_timeout_total(self) -> int: ...

def pin_current_thread_to_cpu(cpu_id: int) -> None: ...
def classify_variant(byte: int) -> Optional[VariantKind]: ...

__version__: str
